# Generated by Django 4.0.4 on 2022-09-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
