version: '3.1'

services:

  db:
    image: postgres
    restart: always
  
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 25032002
      POSTGRES_USER: user
      POSTGRES_DB: tech


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080