# Generated by Django 4.0.4 on 2022-09-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_discount_productreview_productversion_size_tag_and_more'),
        ('basket', '0003_basket_shippingaddress_delete_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='sub_total',
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub-Total')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('basket', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basketitems', to='basket.basket')),
                ('productVersion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Product_Cart', to='product.productversion', verbose_name='Product Version')),
            ],
        ),
    ]
